/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BannerInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Int,
});
export const OrderWithProduct = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'gameId' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Int,
  'product' : Product,
});
export const Banner = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AdminLevel = IDL.Variant({
  'none' : IDL.Null,
  'superAdmin' : IDL.Null,
  'subAdmin' : IDL.Null,
});
export const PaymentSettings = IDL.Record({
  'nagad' : IDL.Text,
  'bkash' : IDL.Text,
  'rocket' : IDL.Text,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'nagad' : IDL.Null,
  'bkash' : IDL.Null,
  'rocket' : IDL.Null,
});
export const Request = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'amount' : IDL.Int,
  'transactionId' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'siteName' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const CreateOrderInput = IDL.Record({
  'gameId' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const RechargeRequestInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'amount' : IDL.Int,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBanner' : IDL.Func([BannerInput], [IDL.Nat], []),
  'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
  'approveRechargeRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'creditWallet' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'deleteBanner' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderWithProduct)], ['query']),
  'getAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
  'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyAdminLevel' : IDL.Func([], [AdminLevel], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderWithProduct)], ['query']),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getRechargeRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserAdminLevel' : IDL.Func([IDL.Principal], [AdminLevel], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([CreateOrderInput], [IDL.Nat], []),
  'rejectRechargeRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAnnouncement' : IDL.Func([IDL.Text], [], []),
  'setPaymentSettings' : IDL.Func([PaymentSettings], [], []),
  'setSiteSettings' : IDL.Func([SiteSettings], [], []),
  'setSubAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'submitRechargeRequest' : IDL.Func([RechargeRequestInput], [IDL.Nat], []),
  'updateBanner' : IDL.Func([IDL.Nat, BannerInput], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BannerInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Int,
  });
  const OrderWithProduct = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'gameId' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Int,
    'product' : Product,
  });
  const Banner = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AdminLevel = IDL.Variant({
    'none' : IDL.Null,
    'superAdmin' : IDL.Null,
    'subAdmin' : IDL.Null,
  });
  const PaymentSettings = IDL.Record({
    'nagad' : IDL.Text,
    'bkash' : IDL.Text,
    'rocket' : IDL.Text,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'nagad' : IDL.Null,
    'bkash' : IDL.Null,
    'rocket' : IDL.Null,
  });
  const Request = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'amount' : IDL.Int,
    'transactionId' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'siteName' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const CreateOrderInput = IDL.Record({
    'gameId' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const RechargeRequestInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'amount' : IDL.Int,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBanner' : IDL.Func([BannerInput], [IDL.Nat], []),
    'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
    'approveRechargeRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'creditWallet' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'deleteBanner' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderWithProduct)], ['query']),
    'getAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
    'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyAdminLevel' : IDL.Func([], [AdminLevel], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderWithProduct)], ['query']),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getRechargeRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserAdminLevel' : IDL.Func([IDL.Principal], [AdminLevel], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Int], ['query']),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([CreateOrderInput], [IDL.Nat], []),
    'rejectRechargeRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAnnouncement' : IDL.Func([IDL.Text], [], []),
    'setPaymentSettings' : IDL.Func([PaymentSettings], [], []),
    'setSiteSettings' : IDL.Func([SiteSettings], [], []),
    'setSubAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'submitRechargeRequest' : IDL.Func([RechargeRequestInput], [IDL.Nat], []),
    'updateBanner' : IDL.Func([IDL.Nat, BannerInput], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };