/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateOrderInput {
  'gameId' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface OrderWithProduct {
  'id' : bigint,
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'gameId' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'totalPrice' : bigint,
  'product' : Product,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'creditWallet' : ActorMethod<[Principal, bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderWithProduct>>,
  'getAnnouncement' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<OrderWithProduct>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[CreateOrderInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAnnouncement' : ActorMethod<[string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];