/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminLevel = { 'none' : null } |
  { 'superAdmin' : null } |
  { 'subAdmin' : null };
export interface Banner {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface BannerInput {
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface CreateOrderInput {
  'gameId' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface OrderWithProduct {
  'id' : bigint,
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'gameId' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'totalPrice' : bigint,
  'product' : Product,
}
export type PaymentMethod = { 'nagad' : null } |
  { 'bkash' : null } |
  { 'rocket' : null };
export interface PaymentSettings {
  'nagad' : string,
  'bkash' : string,
  'rocket' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface RechargeRequestInput {
  'paymentMethod' : PaymentMethod,
  'amount' : bigint,
  'transactionId' : string,
}
export interface Request {
  'id' : bigint,
  'status' : RequestStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : bigint,
  'user' : Principal,
  'amount' : bigint,
  'transactionId' : string,
}
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SiteSettings { 'siteName' : string, 'logoUrl' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBanner' : ActorMethod<[BannerInput], bigint>,
  'addProduct' : ActorMethod<[ProductInput], bigint>,
  'approveRechargeRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'creditWallet' : ActorMethod<[Principal, bigint], undefined>,
  'deleteBanner' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderWithProduct>>,
  'getAnnouncement' : ActorMethod<[], string>,
  'getBanners' : ActorMethod<[], Array<Banner>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyAdminLevel' : ActorMethod<[], AdminLevel>,
  'getMyOrders' : ActorMethod<[], Array<OrderWithProduct>>,
  'getPaymentSettings' : ActorMethod<[], PaymentSettings>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getRechargeRequests' : ActorMethod<[], Array<Request>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserAdminLevel' : ActorMethod<[Principal], AdminLevel>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[CreateOrderInput], bigint>,
  'rejectRechargeRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAnnouncement' : ActorMethod<[string], undefined>,
  'setPaymentSettings' : ActorMethod<[PaymentSettings], undefined>,
  'setSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'setSubAdmin' : ActorMethod<[Principal, boolean], undefined>,
  'submitRechargeRequest' : ActorMethod<[RechargeRequestInput], bigint>,
  'updateBanner' : ActorMethod<[bigint, BannerInput], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];